[package]
name = "qdffri"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
futures = "0.3.30"
qdrant-client = "1.10.2"
serde_json = "1.0.120"
thiserror = "1.0.63"
tokio = { version = "1.39.1", features = ["rt-multi-thread"] }
tonic = "0.12.1"
